spring:
  application:
    name: discodeit
  profiles:
    active: file

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver
    # PostgreSQL createClob() 경고 메시지 제거
    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: discodeit
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 8080

discodeit:
  storage:
    type: local
    local:
      root-path: /path/to/storage/root