spring:
  application:
    name: discodeit
  profiles:
    active: jcf

storage:
  dirs:
    binaryContents: data/binaryContents
    channels: data/channels
    messages: data/messages
    readStatuses: data/readStatuses
    users: data/users
    userStatuses: data/userStatuses