spring:
  application:
    name: discodeit
  profiles:
    active: file

  #파일 관련 설정
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 30MB

  #DB 접속 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    username: discodeit_user
    password: discodeit1234
    driver-class-name: org.postgresql.Driver

  #JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: discodeit
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

#로컬저장소 설정
discodeit:
  storage:
    type: local
    local:
      root-path: /path/to/storage/root