spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/discodeit
    driver-class-name: org.postgresql.Driver
    username: discodeit_user
    password: discodeit1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: discodeit
        ddl-auto: create

  sql:
    init:
      mode: never
      schema-locations: classpath:schema-dev.sql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: TRACE

server:
  port: 8081